### ISSUE TITLE
How to fixe F-Keys when use Bluetooth

### ISSUE THREAD

**Issue by nicolastakashi** [Kurgol/keychron#4]
After I follow the tutorial to configure the F-Keys on Ubuntu everything starts work like a charm when I'm using the KeyBoard by cable.

If I use the KeyBoard with Bluetooth the F-Keys stops to work.

Is there anyone that could help?

**Comment by Kurgol** [comment]
I am sorry but I do not know a solution if anyone does please let us know and I will update the documentation (or send a PR and I will merge it).

**Comment by lucaruzzola** [comment]
Hey there, I love the keyboard, for me too, it does not work under Ubuntu 18.04, the num lock issue arises when using it over bluetooth. Pressing F6 twice does nothing (I don't know which version of the firmware I am running, was this a feature added to some firmware update?). Also, while using the cable, the num pad lock is still on, but the keys are recognized correctly. Any help?

**Comment by Kurgol** [comment]
If I knew a solution in would be in the k2.md! If you manage to find a solution let me know and I will update the repo - I should say this is not affiliated with the Keychron company, I am just a fellow user who wanted to put all my notes in a handy place :)

**Comment by Kurgol** [comment]
@nicolastakashi & @lucaruzzola I have been informed that this might fix it, let me know if it works for you and I will add it to the readme? https://unix.stackexchange.com/questions/121395/on-an-apple-keyboard-under-linux-how-do-i-make-the-function-keys-work-without-t

**Comment by Kurgol** [comment]
I have updated the k2.md to reflect the above article, this fix appears to be working for multiple users in the Keychron Linux Facebook group.
